apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vc-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: views-counter
        tier: frontend
    spec:
      containers:
        - image: gcr.io/views-counter-206010/views-counter:latest
          name: views-counter
          imagePullPolicy: Always
          env:
            - name: REDIS_URI
              value: redis://vc-redis.default.svc.cluster.local:6379
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 3000
              protocol: TCP
