apiVersion: v1
kind: Service
metadata:
  name: vc-app
spec:
  type: LoadBalancer
  sessionAffinity: None
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: views-counter
    tier: frontend
