apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: views-counter
  name: views-counter
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: views-counter
        tier: backend
    spec:
      containers:
        - image: gcr.io/views-counter-206010/views-counter:latest
          name: views-counter
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
