apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vc-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
