
apiVersion: v1
kind: Service
metadata:
  labels:
    app: views-counter
  name: views-counter
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: views-counter
    tier: backend
  sessionAffinity: None
  type: LoadBalancer
