sudo: required
services:
  - docker
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
  - node_modules
env:
  - GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_0aca218c9075_key -iv $encrypted_0aca218c9075_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar

  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/

  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version

  - gcloud auth activate-service-account --key-file gce-credentials.json
  - gcloud config set project views-counter-206010

  - gcloud container clusters get-credentials cluster-1 --zone europe-west1

install: true

script:
  - npm install
  - npm run lint
  - docker image build -t gcr.io/views-counter-206010/views-counter:latest -f dockerfiles/Dockerfile.6 .
  - docker image tag gcr.io/views-counter-206010/views-counter:latest "gcr.io/views-counter-206010/views-counter:$TRAVIS_COMMIT"
  - gcloud docker -- push gcr.io/views-counter-206010/views-counter:latest
  - gcloud docker -- push "gcr.io/views-counter-206010/views-counter:$TRAVIS_COMMIT"
  - kubectl set image deployment/vc-app views-counter="gcr.io/views-counter-206010/views-counter:$TRAVIS_COMMIT"

branches:
  only:
    - master
